on:
  push:
    branches: [main]
    paths: [src/**, test/**, .github/workflows/test.yml]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          runCmd: npm ci && npm test --if-present
