on:
  push:
    branches: [main]
    paths: [docs/**]
  workflow_dispatch:
concurrency:
  group: docs
  cancel-in-progress: true
jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          runCmd: npm ci -w docs && npm pack -w docs --dry-run
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist
      - uses: actions/deploy-pages@v1
        id: deployment
